<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <TargetFramework>net9.0-windows10.0.26100.0</TargetFramework>
    <Nullable>enable</Nullable>
    <UseWPF>true</UseWPF>
    <StartupObject>TableForGto.App</StartupObject>
    <ApplicationIcon>Assets\Images\MainWindowIcon.ico</ApplicationIcon>
  </PropertyGroup>

  <ItemGroup>
    <None Remove="Assets\AddIcon.png" />
    <None Remove="Assets\Images\Add.png" />
    <None Remove="Assets\Images\AddIcon.png" />
    <None Remove="Assets\Images\Calendar.png" />
    <None Remove="Assets\Images\Clock.png" />
    <None Remove="Assets\Images\Column.png" />
    <None Remove="Assets\Images\Menu\Clear.png" />
    <None Remove="Assets\Images\Menu\Copy.png" />
    <None Remove="Assets\Images\Menu\Cut.png" />
    <None Remove="Assets\Images\Menu\Delete.png" />
    <None Remove="Assets\Images\Menu\ExitApp.png" />
    <None Remove="Assets\Images\Menu\NewProject.png" />
    <None Remove="Assets\Images\Menu\OpenProject.png" />
    <None Remove="Assets\Images\Menu\Paste.png" />
    <None Remove="Assets\Images\Menu\Rating.png" />
    <None Remove="Assets\Images\Menu\SaveProject.png" />
    <None Remove="Assets\Images\Menu\SelectAll.png" />
    <None Remove="Assets\Images\Number.png" />
    <None Remove="Assets\Images\Text.png" />
  </ItemGroup>

  <ItemGroup>
    <Resource Include="Assets\Images\Add.png" />
    <Resource Include="Assets\Images\Menu\Clear.png" />
    <Resource Include="Assets\Images\Menu\Copy.png" />
    <Resource Include="Assets\Images\Menu\Cut.png" />
    <Resource Include="Assets\Images\Menu\Delete.png" />
    <Resource Include="Assets\Images\Menu\ExitApp.png" />
    <Resource Include="Assets\Images\Menu\NewProject.png" />
    <Resource Include="Assets\Images\Menu\OpenProject.png" />
    <Resource Include="Assets\Images\Menu\Paste.png" />
    <Resource Include="Assets\Images\Menu\Rating.png" />
    <Resource Include="Assets\Images\Menu\SaveProject.png" />
    <Resource Include="Assets\Images\Menu\SelectAll.png" />
    <Resource Include="Assets\Images\Menu\Calendar.png" />
    <Resource Include="Assets\Images\Menu\Clock.png" />
    <Resource Include="Assets\Images\Menu\Column.png" />
    <Resource Include="Assets\Images\Menu\Number.png" />
    <Resource Include="Assets\Images\Menu\Text.png" />
    <Resource Include="Assets\Images\MainWindowIcon.ico" />
  </ItemGroup>

  <ItemGroup>
    <ApplicationDefinition Update="App.xaml">
      <Generator>MSBuild:Compile</Generator>
    </ApplicationDefinition>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="CommunityToolkit.Mvvm" Version="8.4.0" />
  </ItemGroup>

</Project>
